### ISSUE TITLE
Customize the name of players using input( ) function

### ISSUE THREAD

**Issue by keivalya** [keivalya/pong#2]
Create a customizable name field using the input function or anything you prefer but also make sure it works fine with the existing program or you may modify as per the program's betterment.

**Comment by Apoorve73** [comment]
I would love to work on this!

**Comment by keivalya** [comment]
Extremely nice changes!
Thank you so much for making them. @vjspranav 
Although there are minor issues still prevailing in the code, overall you did very well!

@Apoorve73  I'm really sorry that you couldn't work on this issue. But don't worry, you can still work on certain issues which will come up. I recommend you to fork and clone this repo. Try playing the game, and if you feel like certain changes can be made, you're most welcome.

You can connect with me in the comments or even on LinkedIn
[Keivalya](https://www.linkedin.com/in/keivalya)

Again, thank you both of you for showing interest in this game and participating.
Happy Hacking!

**Comment by Apoorve73** [comment]
That's absolutely fine @keivalya ! Thanks for taking this note! I look forward to work on other issues! :+1:
